allprojects {\n    repositories { google(); mavenCentral() }\n}\nrootProject.buildDir = \"../build\"\nsubprojects { project.buildDir = \"${rootProject.buildDir}/${project.name}\" }\nsubprojects { project.evaluationDependsOn(\":app\") }\ntasks.register(\"clean\", Delete) { delete rootProject.buildDir }